"""empty message

Revision ID: 00a4b2071ecb
Revises: 7212a0b3d548
Create Date: 2025-03-17 15:35:48.489137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a4b2071ecb'
down_revision = '7212a0b3d548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mughals_kitchen',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mughals_kitchen')
    # ### end Alembic commands ###
