"""empty message

Revision ID: 15d934422720
Revises: d7184f34014b
Create Date: 2025-03-19 12:37:22.355448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d934422720'
down_revision = 'd7184f34014b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('resturant_id', sa.Integer(), nullable=False),
    sa.Column('resturant_name', sa.String(length=100), nullable=False),
    sa.Column('resturant_image', sa.String(length=100), nullable=False),
    sa.Column('resturant_description', sa.String(length=100), nullable=False),
    sa.Column('resturant_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('resturant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    # ### end Alembic commands ###
