"""empty message

Revision ID: 63b45b842d43
Revises: 15d934422720
Create Date: 2025-03-20 21:09:09.431584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b45b842d43'
down_revision = '15d934422720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baarista',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('biryani_house',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('dosa_plaza',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('mughals_kitchen',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('punjab_grill',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('restaurant',
    sa.Column('resturant_id', sa.Integer(), nullable=False),
    sa.Column('resturant_name', sa.String(length=100), nullable=False),
    sa.Column('resturant_image', sa.String(length=100), nullable=False),
    sa.Column('resturant_description', sa.String(length=100), nullable=False),
    sa.Column('resturant_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('resturant_id')
    )
    op.create_table('sarwaana_bhawan',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('taj_palace',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taj_palace')
    op.drop_table('sarwaana_bhawan')
    op.drop_table('restaurant')
    op.drop_table('punjab_grill')
    op.drop_table('mughals_kitchen')
    op.drop_table('dosa_plaza')
    op.drop_table('biryani_house')
    op.drop_table('baarista')
    # ### end Alembic commands ###
