"""empty message

Revision ID: b533bd21c0df
Revises: 0362e5069473
Create Date: 2025-03-17 09:52:50.594326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b533bd21c0df'
down_revision = '0362e5069473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taj_palace',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taj_palace')
    # ### end Alembic commands ###
