"""Recreate all tables

Revision ID: d60839ccf820
Revises: 00a4b2071ecb
Create Date: 2025-03-17 21:36:51.251576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60839ccf820'
down_revision = '00a4b2071ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baarista')
    op.drop_table('taj_palace')
    op.drop_table('mughals_kitchen')
    op.drop_table('punjab_grill')
    op.drop_table('biryani_house')
    op.drop_table('sarwaana_bhawan')
    op.drop_table('dosa_plaza')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosa_plaza',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_price', sa.FLOAT(), nullable=False),
    sa.Column('dish_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_rating', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('sarwaana_bhawan',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_price', sa.FLOAT(), nullable=False),
    sa.Column('dish_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_rating', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('biryani_house',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_price', sa.FLOAT(), nullable=False),
    sa.Column('dish_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_rating', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('punjab_grill',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_price', sa.FLOAT(), nullable=False),
    sa.Column('dish_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_rating', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('mughals_kitchen',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_price', sa.FLOAT(), nullable=False),
    sa.Column('dish_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_rating', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('taj_palace',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_price', sa.FLOAT(), nullable=False),
    sa.Column('dish_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_rating', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('baarista',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_price', sa.FLOAT(), nullable=False),
    sa.Column('dish_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dish_rating', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    # ### end Alembic commands ###
