"""empty message

Revision ID: d7184f34014b
Revises: d60839ccf820
Create Date: 2025-03-17 21:40:39.851229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7184f34014b'
down_revision = 'd60839ccf820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baarista',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('biryani_house',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('dosa_plaza',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('mughals_kitchen',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('punjab_grill',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('sarwaana_bhawan',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('taj_palace',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=100), nullable=False),
    sa.Column('dish_price', sa.Float(), nullable=False),
    sa.Column('dish_image', sa.String(length=100), nullable=False),
    sa.Column('dish_description', sa.String(length=100), nullable=False),
    sa.Column('dish_category', sa.String(length=100), nullable=False),
    sa.Column('dish_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taj_palace')
    op.drop_table('sarwaana_bhawan')
    op.drop_table('punjab_grill')
    op.drop_table('mughals_kitchen')
    op.drop_table('dosa_plaza')
    op.drop_table('biryani_house')
    op.drop_table('baarista')
    # ### end Alembic commands ###
